name: Build and Publish Docker images

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch: {}

env:
  APP_IMAGE: ghcr.io/${{ github.repository }}/ai-short-video-app
  REMOTION_IMAGE: ghcr.io/${{ github.repository }}/ai-short-video-remotion

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push app image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.APP_IMAGE }}:latest,${{ env.APP_IMAGE }}:${{ github.ref_name }}

      - name: Build and push remotion image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.remotion
          push: true
          tags: ${{ env.REMOTION_IMAGE }}:latest,${{ env.REMOTION_IMAGE }}:${{ github.ref_name }}
